name: Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to S3
      run: bash scripts/pipeline/release.sh ${{secrets.AWS_S3_BUCKET_NAME}} "deploys/test_one.zip" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_KEY}} "test_one.zip"